### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ghost** [JoeHowse/iOSWithOpenCV#9]
Hi, I updated my macOS and I deleted my old files, now I'm trying to rebuild OpenCV, by your example, but I got this error:

```
RonySteel-iMac:opencv_from_git ronysteel$ ./opencv/platforms/ios/build_framework.py opencv_contrib_source_path/ --contrib opencv_contrib
Executing: ['cmake', '-GXcode', '-DAPPLE_FRAMEWORK=ON', '-DCMAKE_INSTALL_PREFIX=install', '-DCMAKE_BUILD_TYPE=Release', '-DIOS_ARCH=armv7', '-DCMAKE_TOOLCHAIN_FILE=/Users/ronysteel/opencv_from_git/opencv/platforms/ios/cmake/Toolchains/Toolchain-iPhoneOS_Xcode.cmake', '-DENABLE_NEON=ON', '/Users/ronysteel/opencv_from_git/opencv', '-DOPENCV_EXTRA_MODULES_PATH=/Users/ronysteel/opencv_from_git/opencv_contrib/modules', '-DCMAKE_C_FLAGS=-fembed-bitcode', '-DCMAKE_CXX_FLAGS=-fembed-bitcode'] in /Users/ronysteel/opencv_from_git/opencv_contrib_source_path/build/build-armv7-iphoneos
============================================================
ERROR: [Errno 2] No such file or directory
============================================================
Traceback (most recent call last):
  File "./opencv/platforms/ios/build_framework.py", line 112, in build
    self._build(outdir)
  File "./opencv/platforms/ios/build_framework.py", line 104, in _build
    self.buildOne(t[0], t[1], mainBD, cmake_flags)
  File "./opencv/platforms/ios/build_framework.py", line 186, in buildOne
    execute(cmakecmd, cwd = builddir)
  File "./opencv/platforms/ios/build_framework.py", line 36, in execute
    retcode = check_call(cmd, cwd = cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Could you suggest me how to fix that and build your framework, please?

Sincerely,
Rony

**Comment by ghost** [comment]
This error disappear after cmake installation.

Cheers
